import type { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'vubiquity',
    title: 'Vubiquity',
    sub: 'Logo treatment & animation',
    year: '2023',
    client: 'Vubiquity',
    role: 'Motion direction, 2D animation',
    disciplines: ['motion'],
    primary: 'motion',
    featured: true,
    pitch: 'A logo treatment built to survive every screen it lands on.',
    brief:
      'A logo treatment for a media distribution leader that resolves from broadcast static into a singular, confident mark.',
    summary:
      'Identity animation that lives across broadcast end-cards, social, and product surfaces — one motion vocabulary, ten formats.',
    writeup: [
      'Vubiquity needed a logo treatment that read instantly across broadcast, web and product. The constraint: it had to resolve under one second, work in monochrome, and survive both bright and dark surfaces.',
      'I built the animation around a single mechanic — a chromatic separation that resolves into the mark. The same expression rig drives the long-form opener and the social-format bug, so every variant is timing-locked to the same curves.',
      'The deliverable was a small system: a master After Effects project, six pre-rendered formats, and a Lottie export for product surfaces. The animation hooks the rig to a single duration parameter, so future variants stay on brand without re-keying.',
    ],
    hero: { src: '', alt: 'Vubiquity logo animation — final render' },
    heroVideo: 'https://vimeo.com/824804225',
    thumb: { src: '', alt: 'Vubiquity logo animation thumbnail' },
    process: [
      { media: { src: '', alt: '' }, label: 'Frame studies — 24 of 320', note: 'Scribbles + storyboard' },
      { media: { src: '', alt: '' }, label: 'Mark exploration', note: 'Static composition tests' },
      { media: { src: '', alt: '' }, label: 'Timing pass', note: 'After Effects expressions' },
    ],
    tools: 'AE · Lottie · Figma',
    duration: '6 weeks active',
    status: 'Shipped',
    output: 'Broadcast, social, product',
  },
  {
    id: 'multiculturalism',
    title: 'Box of Multiculturalism',
    sub: '3D animation',
    year: '2022',
    client: 'Independent',
    role: '3D direction, animation, lighting',
    disciplines: ['3d', 'motion'],
    primary: '3d',
    pitch: 'One cardboard box. A dozen rituals. What does culture actually contain?',
    brief:
      'A short piece using one cardboard box and a dozen rituals to interrogate the metaphor of cultural containers.',
    summary:
      'A 90-second 3D piece exploring how cultures are packaged, traded and lost. One box. Many languages.',
    writeup: [
      'The brief was self-set: explore what happens when you treat "culture" as something you can put inside a cardboard box and ship somewhere else. The piece works through a single recurring shot — a box, mid-rotation — that opens into different interiors.',
      'I built the rig so the box geometry and camera move are locked, but every interior is a separate scene file. This let me iterate on each ritual independently while keeping the cuts on the same beats.',
      'Lighting was the hard part. Each interior had to read as "somewhere specific" inside three frames, against a neutral exterior. I landed on a fixed three-point setup outside the box and let the interiors handle their own atmospheric haze.',
    ],
    hero: { src: '', alt: 'Box of Multiculturalism — final hero shot' },
    process: [
      { media: { src: '', alt: '' }, label: 'Concept sketches', note: 'Pencil + index cards' },
      { media: { src: '', alt: '' }, label: 'Cinema 4D blocking', note: 'Greybox lighting test' },
      { media: { src: '', alt: '' }, label: 'Texture experiments', note: 'Octane + Substance' },
    ],
    tools: 'C4D · Octane · Substance',
    duration: '8 weeks active',
    status: 'Shipped',
  },
  {
    id: 'xogot',
    title: 'Xogot',
    sub: 'Character & background — 2D game reimagining',
    year: '2024',
    client: 'Xogot',
    role: 'Character design, background art',
    disciplines: ['illo'],
    primary: 'illo',
    brief:
      "A re-imagining of an existing 2D game's visual language — sharper silhouettes, deeper environments, same heart.",
    summary:
      'A visual rebuild of an existing 2D title. New silhouettes, new palette, same playable footprint.',
    writeup: [
      'Xogot wanted to lift the visual ceiling on an existing 2D game without changing the playable footprint. Every new asset had to drop into the same tile size and collision shape as the old one.',
      "I started by stripping the cast down to silhouettes — if a character didn't read from twenty feet away, it didn't move forward. The finalists each carried a single defining feature, which let the background art breathe.",
      'Backgrounds were built in stacks of three layers — foreground, mid, far — so the in-engine parallax does most of the storytelling. The illustration is, in a sense, an afterthought to a tight structural decision.',
    ],
    hero: { src: '', alt: 'Xogot hero character — final render' },
    process: [
      { media: { src: '', alt: '' }, label: 'Silhouette pass', note: '32 thumbnails, 6 finalists' },
      { media: { src: '', alt: '' }, label: 'Environment thumbnails', note: 'Watercolor + digital' },
      { media: { src: '', alt: '' }, label: 'Asset turnarounds', note: 'Game-ready sheets' },
    ],
    tools: 'Procreate · Photoshop · Aseprite',
    duration: '10 weeks active',
    status: 'Shipped',
  },
  {
    id: 'weave',
    title: 'Figma Weave',
    sub: 'Character & world development',
    year: '2024',
    client: 'Self-initiated',
    role: 'Worldbuilding, illustration, motion tests',
    disciplines: ['illo', '3d'],
    primary: 'illo',
    brief:
      'A long-form worldbuilding sandbox: characters, environments, and a small motion language for a fictional cooperative.',
    summary:
      'An ongoing worldbuilding project — characters, biomes, and a small motion vocabulary that ties them together.',
    writeup: [
      'Weave started as a way to test how much worldbuilding I could carry inside Figma alone. The constraint shaped everything — every character, biome and motion test lives in one file, on linked components, with a single design-token sheet.',
      "The interesting discovery was that the constraints of a design tool make for surprisingly rigorous worldbuilding. You can't fudge a culture if every prop is a published component. Every contradiction surfaces immediately.",
      "Motion tests are exported via the Figma → After Effects bridge and rendered into a small loop library. They're not the point of the project, but they make the static frames feel inhabited.",
    ],
    hero: { src: '', alt: 'Weave — world bible hero spread' },
    process: [
      { media: { src: '', alt: '' }, label: 'World map iterations', note: 'Six rounds' },
      { media: { src: '', alt: '' }, label: 'Character lineup', note: 'Cast of twelve' },
      { media: { src: '', alt: '' }, label: 'Motion test reel', note: 'Loop studies' },
    ],
    tools: 'Figma · After Effects · Notion',
    duration: 'Ongoing',
    status: 'Ongoing',
  },
  {
    id: 'bigbake',
    title: 'The Big Bake',
    sub: 'Broadcast animation reel — S1 & S2',
    year: '2022—2023',
    client: 'Food Network',
    role: 'Lead motion designer',
    disciplines: ['motion', 'video'],
    primary: 'motion',
    pitch: 'Two seasons of broadcast graphics, templated for sanity.',
    brief:
      'Two seasons of broadcast graphics, lower-thirds, transitions and end-cards for a competition baking show.',
    summary:
      'Two seasons of broadcast graphics — bumpers, lower-thirds, episode end-cards, scoreboards.',
    writeup: [
      "Broadcast work lives or dies by templating. Two seasons meant roughly 280 unique title cards, scoreboards and bumpers — none of which I'd hand-key without a rig.",
      'The pipeline ended up being four After Effects master comps, parameterised through an expression sheet. The producer fills in a CSV; the comp re-renders. We cut the per-card production time from forty minutes to about six.',
      "The visual language stayed warm and tactile — buttery yellows, soft chrome — to match the show's tone. Restraint was the design choice. The animation vocabulary is small on purpose, so the cast stays the loudest thing on screen.",
    ],
    hero: { src: '', alt: 'The Big Bake — broadcast bumper end frame' },
    process: [
      { media: { src: '', alt: '' }, label: 'Style frames', note: 'Three directions' },
      { media: { src: '', alt: '' }, label: 'Title sequence build', note: 'C4D + AE comp' },
      { media: { src: '', alt: '' }, label: 'Asset pipeline', note: 'Templated AE rigs' },
    ],
    tools: 'After Effects · C4D · CSV pipeline',
    duration: '2 seasons',
    status: 'Shipped',
  },
  {
    id: 'underwriter',
    title: 'Underwriter',
    sub: 'Wealthsimple-styled prototype',
    year: '2025',
    client: 'Independent',
    role: 'Product design, prototype engineering, AI workflows',
    disciplines: ['ai', 'code'],
    primary: 'ai',
    pitch: 'An AI underwriting prototype that surfaces the model instead of hiding it.',
    brief:
      'An AI-assisted underwriting prototype, styled in a fintech idiom — calm, dense, and explicit about confidence.',
    summary:
      'A working AI-underwriting prototype. Document ingestion, structured extraction, and a calm reviewer UI.',
    writeup: [
      'Most AI workflow UI hides the model. Underwriter does the opposite — it surfaces every extraction as a citation, every confidence score as a visible attribute, every model call as a step on the timeline.',
      'I styled the prototype in a fintech idiom because that audience is allergic to surprise. The visual restraint forces the AI behaviour to be the interesting thing, not the chrome.',
      "Under the hood it's a small Claude-driven pipeline with hand-tuned prompts, eval grids for each extraction type, and a deterministic post-processor. The reviewer sees a calm three-column layout. The pipeline behind it is paranoid.",
    ],
    hero: { src: '', alt: 'Underwriter — review screen final state' },
    process: [
      { media: { src: '', alt: '' }, label: 'Information architecture', note: 'Card-sort + flows' },
      { media: { src: '', alt: '' }, label: 'Prompt workbench', note: 'Eval grid' },
      { media: { src: '', alt: '' }, label: 'UI calibration', note: 'Confidence badging' },
    ],
    tools: 'Next.js · Claude · TypeScript',
    duration: '5 weeks active',
    status: 'Prototype',
  },
  {
    id: 'reels',
    title: 'Animation Reel',
    sub: 'Nikki Ray & Architect Films',
    year: '2021—2024',
    client: 'Various',
    role: 'Motion design, broadcast graphics',
    disciplines: ['motion', 'video'],
    primary: 'video',
    brief:
      'Selected animation work across documentary, lifestyle and brand projects for two production houses.',
    summary: 'Compilation reel — selected motion and titling for documentary, lifestyle and brand work.',
    writeup: [
      'Reels are an editing problem more than a motion problem. The temptation is to put your loudest frames first; the better move is to pace it like a piece of music.',
      'I cut to a single track and let the motion vocabulary cluster — broadcast intros up front, then documentary titles, then experimental loops. Each block has its own visual logic, but the cuts thread on rhythm.',
      "Color and sound got a final unifying pass. One LUT across everything, one stereo mix, one master at three deliverables. Simple discipline, but it's why the reel reads as a single voice.",
    ],
    hero: { src: '', alt: 'Animation Reel — title card' },
    process: [
      { media: { src: '', alt: '' }, label: 'Reel cut breakdown', note: '120 → 90 seconds' },
      { media: { src: '', alt: '' }, label: 'Color pass', note: 'DaVinci — single LUT' },
      { media: { src: '', alt: '' }, label: 'Sound design', note: 'Two-track mix' },
    ],
    tools: 'Premiere · DaVinci · After Effects',
    duration: 'Rolling',
    status: 'Updated quarterly',
  },
  {
    id: 'modelling',
    title: '3D Modelling Showcase',
    sub: 'Hard-surface & character',
    year: '2024—2025',
    client: 'Self-initiated',
    role: 'Modeller, texture, render',
    disciplines: ['3d'],
    primary: '3d',
    brief:
      'An evolving showcase of hard-surface and character modelling — production-ready topology, no shortcut sculpts.',
    summary: 'An open showcase of hard-surface and character work — wires, turntables, breakdowns.',
    writeup: [
      'The work in here is deliberately unstyled — production-ready topology, clean UVs, baked textures. The point is to show I can hand a model off, not just light a beautiful turntable.',
      'Each asset includes wireframes, UV layouts, and a breakdown of decisions: where I sculpted vs. floated detail, where I baked vs. modelled, what the polycount budget was and why.',
      "It's an ongoing log. I add a new piece roughly every six weeks, with a short note about what I was trying to learn — generally a specific topology or shader trick rather than a finished hero shot.",
    ],
    hero: { src: '', alt: '3D modelling — hard-surface turntable' },
    process: [
      { media: { src: '', alt: '' }, label: 'Reference board', note: 'Per asset' },
      { media: { src: '', alt: '' }, label: 'Block-out → high-poly', note: 'ZBrush + Blender' },
      { media: { src: '', alt: '' }, label: 'Bake & shade', note: 'Substance + Octane' },
    ],
    tools: 'Blender · ZBrush · Substance · Octane',
    duration: 'Ongoing',
    status: 'Ongoing',
  },
];
