#!/usr/bin/env node
/* ──────────────────────────────────────────────────────────────────────────
 * Build-time codegen: read /data mdoc collections into JSON bundles.
 *
 * JSON singletons (data/site.json, data/editorial.json, etc.) are imported
 * directly by content/*.ts via webpack's JSON loader — no codegen needed.
 *
 * Mdoc collections (data/notes/<slug>/index.mdoc, data/projects/<slug>/...)
 * are pre-parsed here and written to data/_generated/<name>.json, which
 * content/*.ts then imports the same way.
 *
 * Run via:
 *   - `pnpm prebuild`  (hook for pnpm build)
 *   - `pnpm predev`    (hook for pnpm dev)
 *   - directly: `node scripts/generate-content.mjs`
 *
 * Keystatic writes the source mdoc files; this script keeps the JSON the
 * client bundle imports in sync.
 * ──────────────────────────────────────────────────────────────────────── */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'data');
const OUT = path.join(DATA, '_generated');

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function readMdocCollection(dirName) {
  const root = path.join(DATA, dirName);
  if (!fs.existsSync(root)) return [];
  const slugs = fs
    .readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
    .map((d) => d.name)
    .sort();

  const entries = [];
  for (const slug of slugs) {
    const file = path.join(root, slug, 'index.mdoc');
    if (!fs.existsSync(file)) continue;
    const raw = fs.readFileSync(file, 'utf8');
    const { data: frontmatter, content } = matter(raw);
    entries.push({
      slug,
      frontmatter,
      body: content.trim(),
    });
  }
  return entries;
}

function writeJSON(name, payload) {
  const file = path.join(OUT, `${name}.json`);
  fs.writeFileSync(file, JSON.stringify(payload, null, 2));
  console.log(
    `  → wrote ${path.relative(ROOT, file)}  (${(payload.length ?? Object.keys(payload).length)} entries)`,
  );
}

function main() {
  console.log('▸ Generating content from /data');
  ensureDir(OUT);

  const notes = readMdocCollection('notes');
  writeJSON('notes', notes);

  const projects = readMdocCollection('projects');
  writeJSON('projects', projects);

  /* Drop a README so editors who stumble in know not to hand-edit the
   * generated artefacts. */
  fs.writeFileSync(
    path.join(OUT, 'README.md'),
    [
      '# /data/_generated',
      '',
      'This folder is regenerated by `scripts/generate-content.mjs`.',
      'Do not edit by hand — your changes will be overwritten on the next',
      '`pnpm build` or `pnpm dev`. Edit the source `.mdoc` files in the',
      'parent `data/notes/` and `data/projects/` directories instead, or',
      'use the Keystatic admin at `/keystatic`.',
      '',
    ].join('\n'),
  );

  console.log('✓ Content bundles ready.');
}

main();
